// dfwl/game/dfwlgame-25/src/App.tsx
import { useEffect, useRef, useState } from "react";
import { game as gameMeta } from "./gameMeta";

const game = gameMeta as {
  title: string;
  subtitle: string;
  stack: readonly string[];
  storageKey: string;
  accent: string;
  type: string;
};

type RunState = "ready" | "playing" | "paused" | "over" | "won";

type Actor = { x: number; y: number; w: number; h: number; vx?: number; vy?: number; alive?: boolean };

const width = 900;
const height = 560;

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value));
}

function hit(a: Actor, b: Actor) {
  return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
}

export default function App() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const keys = useRef(new Set<string>());
  const frame = useRef(0);
  const [runState, setRunState] = useState<RunState>("ready");
  const [score, setScore] = useState(0);
  const [lives, setLives] = useState(3);
  const [best, setBest] = useState(() => Number(localStorage.getItem(game.storageKey) || 0));
  const [message, setMessage] = useState("按开始进入游戏。");

  const state = useRef({
    player: { x: 410, y: 480, w: 84, h: 28, vx: 0, vy: 0 },
    bird: { x: 170, y: 240, w: 34, h: 34, vy: 0 },
    items: [] as Actor[],
    bullets: [] as Actor[],
    bricks: Array.from({ length: 24 }, (_, i) => ({ x: 60 + (i % 8) * 98, y: 52 + Math.floor(i / 8) * 34, w: 76, h: 22, alive: true })),
    ball: { x: 430, y: 320, w: 18, h: 18, vx: 4, vy: -4 },
    tick: 0
  });

  function reset() {
    state.current = {
      player: { x: 410, y: 480, w: 84, h: 28, vx: 0, vy: 0 },
      bird: { x: 170, y: 240, w: 34, h: 34, vy: 0 },
      items: [],
      bullets: [],
      bricks: Array.from({ length: 24 }, (_, i) => ({ x: 60 + (i % 8) * 98, y: 52 + Math.floor(i / 8) * 34, w: 76, h: 22, alive: true })),
      ball: { x: 430, y: 320, w: 18, h: 18, vx: 4, vy: -4 },
      tick: 0
    };
    setScore(0);
    setLives(3);
    setRunState("playing");
    setMessage("游戏进行中。");
  }

  function finish(nextScore: number, text: string, state: RunState = "over") {
    setRunState(state);
    setMessage(text);
    setBest((old) => {
      const value = Math.max(old, nextScore);
      localStorage.setItem(game.storageKey, String(value));
      return value;
    });
  }

  useEffect(() => {
    const down = (event: KeyboardEvent) => {
      keys.current.add(event.key);
      if (event.key === " " && game.type === "flappy") state.current.bird.vy = -8;
    };
    const up = (event: KeyboardEvent) => keys.current.delete(event.key);
    window.addEventListener("keydown", down);
    window.addEventListener("keyup", up);
    return () => {
      window.removeEventListener("keydown", down);
      window.removeEventListener("keyup", up);
    };
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;

    const drawActor = (actor: Actor, color: string) => {
      ctx.fillStyle = color;
      ctx.fillRect(actor.x, actor.y, actor.w, actor.h);
    };

    const loop = () => {
      frame.current = requestAnimationFrame(loop);
      ctx.clearRect(0, 0, width, height);
      ctx.fillStyle = "#020617";
      ctx.fillRect(0, 0, width, height);
      ctx.strokeStyle = game.accent;
      ctx.strokeRect(12, 12, width - 24, height - 24);

      if (runState !== "playing") {
        ctx.fillStyle = "#dbeafe";
        ctx.font = "28px sans-serif";
        ctx.fillText(message, 40, 72);
        return;
      }

      const s = state.current;
      s.tick += 1;

      const player = s.player;
      if (keys.current.has("ArrowLeft") || keys.current.has("a")) player.x -= 8;
      if (keys.current.has("ArrowRight") || keys.current.has("d")) player.x += 8;
      player.x = clamp(player.x, 20, width - player.w - 20);
      if (s.tick % 42 === 0) s.items.push({ x: 30 + Math.random() * (width - 80), y: 0, w: 24, h: 24, vy: 3 + Math.random() * 3 });
      s.items.forEach((item) => item.y += item.vy || 0);
      s.items = s.items.filter((item) => {
        if (hit(item, player)) {
          setScoreSafe(score + 10);
          return false;
        }
        if (item.y > height) {
          loseLife();
          return false;
        }
        return true;
      });
      drawActor(player, game.accent);
      s.items.forEach((item) => drawActor(item, "#fde68a"));
      
      
      
    };

    frame.current = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(frame.current);
  }, [runState, message]);

  return (
    <main className="app" style={{ "--accent": game.accent } as React.CSSProperties}>
      <div className="shell">
        <header className="topbar">
          <div>
            <p className="eyebrow">前端游戏最小闭环</p>
            <h1>{game.title}</h1>
            <p className="subtitle">{game.subtitle}</p>
          </div>
          <div className="stack">{game.stack.map((item) => <span className="tag" key={item}>{item}</span>)}</div>
        </header>
        <section className="hud">
          <div className="stat"><span>分数</span><strong>{score}</strong></div>
          <div className="stat"><span>生命</span><strong>{lives}</strong></div>
          <div className="stat"><span>最高分</span><strong>{best}</strong></div>
          <div className="stat"><span>状态</span><strong>{runState}</strong></div>
        </section>
        <section className="layout">
          <div className="stage"><canvas ref={canvasRef} width={width} height={height} onPointerDown={() => { if (game.type === "flappy") state.current.bird.vy = -8; }} /></div>
          <aside className="side">
            <div className="controls">
              <button className="primary" onClick={reset}>开始/重开</button>
              <button onClick={() => setRunState((s) => s === "playing" ? "paused" : "playing")}>暂停/继续</button>
            </div>
            <p className="hint">方向键或A/D控制移动，空格用于跳跃或射击。当前项目保留了最小闭环，后续可以继续扩展关卡、素材和音效。</p>
            <div className="result">{message}</div>
          </aside>
        </section>
      </div>
    </main>
  );

  function setScoreSafe(next: number) {
    setScore(next);
    return next;
  }

  function loseLife() {
    setLives((current) => {
      const next = current - 1;
      if (next <= 0) finish(score, "生命耗尽，挑战结束。");
      return Math.max(0, next);
    });
  }
}

// hxwl/game/hxwlgame-30/src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { game } from "./gameMeta";

const colors = ["#ef4444", "#3b82f6", "#22c55e", "#eab308", "#a855f7"];
const board = ref<string[]>([]);
const score = ref(0);
const moves = ref(24);
const target = 520;
const best = ref(Number(localStorage.getItem(game.storageKey) || 0));
const status = computed(() => score.value >= target ? "胜利" : moves.value <= 0 ? "失败" : "进行中");

function reset() {
  board.value = Array.from({ length: 49 }, () => colors[Math.floor(Math.random() * colors.length)]);
  score.value = 0;
  moves.value = 24;
}

function neighbors(index: number) {
  const row = Math.floor(index / 7);
  const col = index % 7;
  return [index - 7, index + 7, col > 0 ? index - 1 : -1, col < 6 ? index + 1 : -1].filter((item) => item >= 0 && item < 49);
}

function pop(index: number) {
  if (status.value !== "进行中") return;
  const color = board.value[index];
  const group = new Set<number>([index]);
  const queue = [index];
  while (queue.length) {
    const current = queue.shift()!;
    for (const next of neighbors(current)) {
      if (!group.has(next) && board.value[next] === color) {
        group.add(next);
        queue.push(next);
      }
    }
  }
  if (group.size < 2) return;
  moves.value -= 1;
  score.value += group.size * group.size * 5;
  group.forEach((item) => board.value[item] = colors[Math.floor(Math.random() * colors.length)]);
  if (score.value > best.value) {
    best.value = score.value;
    localStorage.setItem(game.storageKey, String(best.value));
  }
}

reset();
</script>

<template><main class="app" :style="{ '--accent': game.accent }">
    <div class="shell">
      <header class="topbar">
        <div>
          <p class="eyebrow">前端游戏最小闭环</p>
          <h1>{{ game.title }}</h1>
          <p class="subtitle">{{ game.subtitle }}</p>
        </div>
        <div class="stack"><span v-for="item in game.stack" :key="item" class="tag">{{ item }}</span></div>
      </header>
      <section class="hud">
        <div class="stat"><span>分数/生命</span><strong>{{ typeof score !== 'undefined' ? score : playerHp }}</strong></div>
        <div class="stat"><span>步数/能量</span><strong>{{ typeof steps !== 'undefined' ? steps : typeof moves !== 'undefined' ? moves : energy }}</strong></div>
        <div class="stat"><span>用时/目标</span><strong>{{ typeof seconds !== 'undefined' ? seconds : typeof target !== 'undefined' ? target : enemyHp }}</strong></div>
        <div class="stat"><span>最佳</span><strong>{{ typeof best !== 'undefined' ? best : history.length }}</strong></div>
      </section>
      <section class="layout">
        <div class="stage"><div class="board blocks">
            <div v-for="(color, index) in board" :key="index" class="tile" :style="{ background: color }" @click="pop(index)"></div>
          </div></div>
        <aside class="side"><div class="controls"><button class="primary" @click="reset">重新开局</button></div>
          <p class="hint">点击两个以上相邻同色方块消除，分数达到{{ target }}即胜利。</p>
          <div class="result">当前状态：{{ status }}</div></aside>
      </section>
    </div>
  </main>
</template>
