// hxwl/data-visualization/hxwldataviz-37/src/App.tsx
import { FormEvent, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Field = {
  key: string;
  label: string;
  type?: "number" | "date" | "select";
  options?: string[];
};

type RecordItem = {
  id: string;
  note: string;
  [key: string]: string | number;
};

const project = {
  "name": "hxwldataviz-37",
  "folder": "hxwl/data-visualization/hxwldataviz-37",
  "framework": "react",
  "chartLib": "ECharts",
  "ui": "Ant Design",
  "title": "运营漏斗分析面板",
  "subtitle": "观察访问、注册、下单、支付的转化率和渠道差异。",
  "stack": [
    "React",
    "Vite",
    "TypeScript",
    "Ant Design",
    "ECharts"
  ],
  "storageKey": "hxwldataviz-37-funnel",
  "theme": "#7c3aed",
  "prompt": "使用React、Vite、TypeScript、Ant Design和ECharts实现一个运营漏斗分析面板，内置访问、注册、下单、支付四个环节的数据，展示漏斗转化率、环节流失数和分渠道对比。支持按渠道筛选，并在点击某个漏斗环节时展示该环节的明细说明和改进建议。",
  "filters": {
    "primaryLabel": "渠道",
    "primaryKey": "channel",
    "primaryOptions": [
      "全部渠道",
      "自然流量",
      "广告投放",
      "社群",
      "短信召回"
    ],
    "secondaryLabel": "周期",
    "secondaryKey": "period",
    "secondaryOptions": [
      "全部周期",
      "本周",
      "上周"
    ]
  },
  "fields": [
    {
      "key": "period",
      "label": "周期",
      "type": "select",
      "options": [
        "本周",
        "上周"
      ]
    },
    {
      "key": "channel",
      "label": "渠道",
      "type": "select",
      "options": [
        "自然流量",
        "广告投放",
        "社群",
        "短信召回"
      ]
    },
    {
      "key": "visits",
      "label": "访问",
      "type": "number"
    },
    {
      "key": "registered",
      "label": "注册",
      "type": "number"
    },
    {
      "key": "ordered",
      "label": "下单",
      "type": "number"
    },
    {
      "key": "paid",
      "label": "支付",
      "type": "number"
    }
  ],
  "records": [
    {
      "period": "本周",
      "channel": "自然流量",
      "visits": 12600,
      "registered": 4100,
      "ordered": 1560,
      "paid": 1120,
      "note": "支付页转化稳定"
    },
    {
      "period": "本周",
      "channel": "广告投放",
      "visits": 18200,
      "registered": 5200,
      "ordered": 1680,
      "paid": 980,
      "note": "下单后流失偏高"
    },
    {
      "period": "本周",
      "channel": "社群",
      "visits": 7600,
      "registered": 3200,
      "ordered": 1410,
      "paid": 1040,
      "note": "高意向渠道"
    },
    {
      "period": "上周",
      "channel": "短信召回",
      "visits": 4900,
      "registered": 1300,
      "ordered": 480,
      "paid": 260,
      "note": "触达质量一般"
    }
  ],
  "metricLabels": [
    "访问",
    "注册率",
    "支付率",
    "最大流失"
  ]
} as const;
const fields = project.fields as unknown as Field[];

function monthFromDate(value: string) {
  return value.slice(0, 7);
}

function withIds(): RecordItem[] {
  return project.records.map((record, index) => ({
    ...record,
    id: `seed-${index + 1}`
  })) as RecordItem[];
}

function normalizeRecord(form: Record<string, string | number>, note: string): RecordItem {
  const next = { ...form } as RecordItem;
  next.id = crypto.randomUUID();
  next.note = note || "本地新增记录";
  if ("date" in next && !("month" in next)) next.month = monthFromDate(String(next.date));
  return next;
}

function loadRecords(): RecordItem[] {
  const raw = localStorage.getItem(project.storageKey);
  if (!raw) return withIds();
  try {
    return JSON.parse(raw) as RecordItem[];
  } catch {
    return withIds();
  }
}

function createBlank() {
  return Object.fromEntries(fields.map((field) => [field.key, field.type === "number" ? 0 : ""]));
}

function sum(records: RecordItem[], key: string) {
  return records.reduce((acc, record) => acc + Number(record[key] || 0), 0);
}

function groupSum(records: RecordItem[], groupKey: string, valueKey: string) {
  const map = new Map<string, number>();
  records.forEach((record) => {
    const key = String(record[groupKey] || "未分类");
    map.set(key, (map.get(key) || 0) + Number(record[valueKey] || 0));
  });
  return Array.from(map, ([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
}

function filterRecords(records: RecordItem[], primary: string, secondary: string) {
  return records.filter((record) => {
    const primaryOk = primary.startsWith("全部") || record[project.filters.primaryKey] === primary;
    const secondaryOk = secondary.startsWith("全部") || record[project.filters.secondaryKey] === secondary;
    return primaryOk && secondaryOk;
  });
}


const steps = [
  { key: "visits", label: "访问" },
  { key: "registered", label: "注册" },
  { key: "ordered", label: "下单" },
  { key: "paid", label: "支付" }
];

export default function App() {
  const [records, setRecords] = useState<RecordItem[]>(loadRecords);
  const [form, setForm] = useState<Record<string, string | number>>(createBlank);
  const [note, setNote] = useState("");
  const [primary, setPrimary] = useState<string>(project.filters.primaryOptions[0]);
  const [secondary, setSecondary] = useState<string>(project.filters.secondaryOptions[0]);
  const [selected, setSelected] = useState("registered");
  const filtered = useMemo(() => filterRecords(records, primary, secondary), [records, primary, secondary]);

  const funnel = steps.map((step) => ({ name: step.label, key: step.key, value: sum(filtered, step.key) }));
  const visits = funnel[0]?.value || 0;
  const paid = funnel[3]?.value || 0;
  const maxLoss = Math.max(0, ...funnel.slice(0, -1).map((item, index) => item.value - funnel[index + 1].value));
  const selectedStep = funnel.find((item) => item.key === selected) || funnel[1];
  const suggestion = selected === "registered" ? "优化首屏价值表达和注册入口。" : selected === "ordered" ? "检查商品详情页和下单路径阻力。" : selected === "paid" ? "关注支付方式、优惠展示和失败重试。" : "提升渠道落地页相关性。";

  function persist(next: RecordItem[]) {
    setRecords(next);
    localStorage.setItem(project.storageKey, JSON.stringify(next));
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    persist([normalizeRecord(form, note), ...records]);
    setForm(createBlank());
    setNote("");
  }

  return (
    <main className="app" style={{ "--theme": project.theme } as React.CSSProperties}>
      <div className="shell">
        <header className="topbar">
          <div><p className="eyebrow">数据分析与可视化</p><h1>{project.title}</h1><p className="subtitle">{project.subtitle}</p></div>
          <div className="stack">{project.stack.map((item) => <span className="tag" key={item}>{item}</span>)}</div>
        </header>
        <section className="filters">
          <label>{project.filters.primaryLabel}<select value={primary} onChange={(event) => setPrimary(event.target.value)}>{project.filters.primaryOptions.map((item) => <option key={item}>{item}</option>)}</select></label>
          <label>{project.filters.secondaryLabel}<select value={secondary} onChange={(event) => setSecondary(event.target.value)}>{project.filters.secondaryOptions.map((item) => <option key={item}>{item}</option>)}</select></label>
          <label>漏斗环节<select value={selected} onChange={(event) => setSelected(event.target.value)}>{steps.map((item) => <option value={item.key} key={item.key}>{item.label}</option>)}</select></label>
        </section>
        <section className="metrics">
          <article className="metric"><span>{project.metricLabels[0]}</span><strong>{visits}</strong></article>
          <article className="metric"><span>{project.metricLabels[1]}</span><strong>{visits ? Math.round((sum(filtered, "registered") / visits) * 100) : 0}%</strong></article>
          <article className="metric"><span>{project.metricLabels[2]}</span><strong>{visits ? Math.round((paid / visits) * 100) : 0}%</strong></article>
          <article className="metric"><span>{project.metricLabels[3]}</span><strong>{maxLoss}</strong></article>
        </section>
        <section className="chart-grid">
          <article className="chart-card">
            <h2>漏斗转化</h2>
            <div className="simple-chart">{funnel.map((row) => <div className="bar" key={row.key}><span>{row.name}</span><div className="track"><div className="fill" style={{ width: `${visits ? (row.value / visits) * 100 : 0}%` }} /></div><strong>{row.value}</strong></div>)}</div>
          </article>
          <article className="chart-card">
            <h2>分渠道对比</h2>
            <div className="chart">
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={filtered}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="channel" /><YAxis /><Tooltip /><Bar dataKey="paid" fill={project.theme} /></BarChart>
              </ResponsiveContainer>
            </div>
            <div className="insight">{selectedStep.name}当前量级为{selectedStep.value}。{suggestion}</div>
          </article>
        </section>
        <section className="workspace">
          <form className="panel" onSubmit={submit}>
            <h2>新增渠道数据</h2>
            <div className="form-grid">{fields.map((field) => <label key={field.key}>{field.label}{field.type === "select" ? <select required value={String(form[field.key])} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}><option value="">请选择</option>{field.options?.map((item) => <option key={item}>{item}</option>)}</select> : <input required type={field.type || "text"} value={form[field.key]} onChange={(event) => setForm({ ...form, [field.key]: field.type === "number" ? Number(event.target.value) : event.target.value })} />}</label>)}<label>备注<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><button type="submit">保存并刷新</button></div>
          </form>
          <section className="table-panel"><h2>渠道明细</h2><table><thead><tr>{fields.map((field) => <th key={field.key}>{field.label}</th>)}<th>备注</th></tr></thead><tbody>{filtered.map((record) => <tr key={record.id}>{fields.map((field) => <td key={field.key}>{record[field.key]}</td>)}<td className="note">{record.note}</td></tr>)}</tbody></table></section>
        </section>
      </div>
    </main>
  );
}

// hxwl/data-visualization/hxwldataviz-38/src/App.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, reactive, watch } from "vue";
import { Chart } from "@antv/g2";

type Field = {
  key: string;
  label: string;
  type?: "number" | "date" | "select";
  options?: string[];
};

type RecordItem = {
  id: string;
  note: string;
  [key: string]: string | number;
};

const project = {
  "name": "hxwldataviz-38",
  "folder": "hxwl/data-visualization/hxwldataviz-38",
  "framework": "vue",
  "chartLib": "AntV G2",
  "ui": "Element Plus",
  "title": "库存周转分析看板",
  "subtitle": "分析SKU库存、出库趋势、低库存预警和周转排名。",
  "stack": [
    "Vue3",
    "Vite",
    "TypeScript",
    "Element Plus",
    "AntV G2"
  ],
  "storageKey": "hxwldataviz-38-inventory",
  "theme": "#dc2626",
  "prompt": "使用Vue3、Vite、TypeScript、Element Plus和AntV G2实现一个库存周转分析看板，内置SKU库存、入库、出库和安全库存数据，展示库存总量、近7天出库趋势、低库存预警和SKU周转排名。支持按仓库筛选，新增一条出入库记录后需要重新计算全部指标。",
  "filters": {
    "primaryLabel": "仓库",
    "primaryKey": "warehouse",
    "primaryOptions": [
      "全部仓库",
      "上海仓",
      "杭州仓",
      "成都仓"
    ],
    "secondaryLabel": "类型",
    "secondaryKey": "operation",
    "secondaryOptions": [
      "全部类型",
      "入库",
      "出库"
    ]
  },
  "fields": [
    {
      "key": "date",
      "label": "日期",
      "type": "date"
    },
    {
      "key": "warehouse",
      "label": "仓库",
      "type": "select",
      "options": [
        "上海仓",
        "杭州仓",
        "成都仓"
      ]
    },
    {
      "key": "sku",
      "label": "SKU"
    },
    {
      "key": "operation",
      "label": "类型",
      "type": "select",
      "options": [
        "入库",
        "出库"
      ]
    },
    {
      "key": "quantity",
      "label": "数量",
      "type": "number"
    },
    {
      "key": "safeStock",
      "label": "安全库存",
      "type": "number"
    }
  ],
  "records": [
    {
      "date": "2026-06-24",
      "warehouse": "上海仓",
      "sku": "SKU-1008",
      "operation": "入库",
      "quantity": 320,
      "safeStock": 180,
      "note": "补货入库"
    },
    {
      "date": "2026-06-25",
      "warehouse": "上海仓",
      "sku": "SKU-1008",
      "operation": "出库",
      "quantity": 260,
      "safeStock": 180,
      "note": "大客户出库"
    },
    {
      "date": "2026-06-26",
      "warehouse": "杭州仓",
      "sku": "SKU-2217",
      "operation": "出库",
      "quantity": 190,
      "safeStock": 220,
      "note": "库存偏低"
    },
    {
      "date": "2026-06-29",
      "warehouse": "成都仓",
      "sku": "SKU-3302",
      "operation": "入库",
      "quantity": 410,
      "safeStock": 260,
      "note": "区域补货"
    },
    {
      "date": "2026-06-30",
      "warehouse": "杭州仓",
      "sku": "SKU-2217",
      "operation": "出库",
      "quantity": 90,
      "safeStock": 220,
      "note": "继续消耗"
    }
  ],
  "metricLabels": [
    "库存净量",
    "出库量",
    "低库存SKU",
    "周转SKU"
  ]
} as const;
const fields = project.fields as unknown as Field[];

function monthFromDate(value: string) {
  return value.slice(0, 7);
}

function withIds(): RecordItem[] {
  return project.records.map((record, index) => ({
    ...record,
    id: `seed-${index + 1}`
  })) as RecordItem[];
}

function normalizeRecord(form: Record<string, string | number>, note: string): RecordItem {
  const next = { ...form } as RecordItem;
  next.id = crypto.randomUUID();
  next.note = note || "本地新增记录";
  if ("date" in next && !("month" in next)) next.month = monthFromDate(String(next.date));
  return next;
}

function loadRecords(): RecordItem[] {
  const raw = localStorage.getItem(project.storageKey);
  if (!raw) return withIds();
  try {
    return JSON.parse(raw) as RecordItem[];
  } catch {
    return withIds();
  }
}

function createBlank() {
  return Object.fromEntries(fields.map((field) => [field.key, field.type === "number" ? 0 : ""]));
}

function sum(records: RecordItem[], key: string) {
  return records.reduce((acc, record) => acc + Number(record[key] || 0), 0);
}

function groupSum(records: RecordItem[], groupKey: string, valueKey: string) {
  const map = new Map<string, number>();
  records.forEach((record) => {
    const key = String(record[groupKey] || "未分类");
    map.set(key, (map.get(key) || 0) + Number(record[valueKey] || 0));
  });
  return Array.from(map, ([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
}

function filterRecords(records: RecordItem[], primary: string, secondary: string) {
  return records.filter((record) => {
    const primaryOk = primary.startsWith("全部") || record[project.filters.primaryKey] === primary;
    const secondaryOk = secondary.startsWith("全部") || record[project.filters.secondaryKey] === secondary;
    return primaryOk && secondaryOk;
  });
}


const records = ref<RecordItem[]>(loadRecords());
const form = reactive<Record<string, string | number>>(createBlank());
const note = ref("");
const primary = ref(project.filters.primaryOptions[0]);
const secondary = ref(project.filters.secondaryOptions[0]);
const chartA = ref<HTMLDivElement | null>(null);
const chartB = ref<HTMLDivElement | null>(null);
let chartOne: any = null;
let chartTwo: any = null;

const filtered = computed(() => filterRecords(records.value, primary.value, secondary.value));
const totalAmount = computed(() => sum(filtered.value, "amount") || sum(filtered.value, "quantity"));
const totalQuantity = computed(() => sum(filtered.value, "quantity"));
const groupPrimary = computed(() => groupSum(filtered.value, project.filters.primaryKey, "amount").length ? groupSum(filtered.value, project.filters.primaryKey, "amount") : groupSum(filtered.value, project.filters.primaryKey, "quantity"));
const groupSecondary = computed(() => groupSum(filtered.value, project.filters.secondaryKey, "amount").length ? groupSum(filtered.value, project.filters.secondaryKey, "amount") : groupSum(filtered.value, project.filters.secondaryKey, "quantity"));
const lowStock = computed(() => filtered.value.filter((record) => record.operation === "出库" && Number(record.quantity) >= Number(record.safeStock || 0)).length);

function persist() {
  localStorage.setItem(project.storageKey, JSON.stringify(records.value));
}

function submit() {
  records.value = [normalizeRecord(form, note.value), ...records.value];
  Object.assign(form, createBlank());
  note.value = "";
  persist();
  nextTick(renderCharts);
}

function resetFilter() {
  primary.value = project.filters.primaryOptions[0];
  secondary.value = project.filters.secondaryOptions[0];
}

function renderCharts() {
  if (!chartA.value || !chartB.value) return;
  chartA.value.innerHTML = "";
  chartB.value.innerHTML = "";
  chartOne = new Chart({ container: chartA.value, autoFit: true, height: 280 });
  chartOne.data(groupPrimary.value);
  chartOne.interval().encode("x", "name").encode("y", "value").style("fill", project.theme);
  chartOne.render();
  chartTwo = new Chart({ container: chartB.value, autoFit: true, height: 280 });
  chartTwo.data(groupSecondary.value);
  chartTwo.interval().encode("x", "name").encode("y", "value").style("fill", project.theme);
  chartTwo.render();
}

onMounted(renderCharts);
watch(filtered, () => nextTick(renderCharts), { deep: true });
</script>

<template>
  <main class="app" :style="{ '--theme': project.theme }">
    <div class="shell">
      <header class="topbar">
        <div>
          <p class="eyebrow">数据分析与可视化</p>
          <h1>{{ project.title }}</h1>
          <p class="subtitle">{{ project.subtitle }}</p>
        </div>
        <div class="stack"><span v-for="item in project.stack" :key="item" class="tag">{{ item }}</span></div>
      </header>

      <section class="filters">
        <label>{{ project.filters.primaryLabel }}<select v-model="primary"><option v-for="item in project.filters.primaryOptions" :key="item">{{ item }}</option></select></label>
        <label>{{ project.filters.secondaryLabel }}<select v-model="secondary"><option v-for="item in project.filters.secondaryOptions" :key="item">{{ item }}</option></select></label>
        <button class="secondary" type="button" @click="resetFilter">重置筛选</button>
      </section>

      <section class="metrics">
        <article class="metric"><span>{{ project.metricLabels[0] }}</span><strong>{{ totalAmount }}</strong></article>
        <article class="metric"><span>{{ project.metricLabels[1] }}</span><strong>{{ totalQuantity }}</strong></article>
        <article class="metric"><span>{{ project.metricLabels[2] }}</span><strong>{{ lowStock }}</strong></article>
        <article class="metric"><span>{{ project.metricLabels[3] }}</span><strong>{{ groupSecondary[0]?.name || '无' }}</strong></article>
      </section>

      <section class="chart-grid">
        <article class="chart-card"><h2>趋势分析</h2><div ref="chartA" class="chart"></div></article>
        <article class="chart-card"><h2>结构分布</h2><div ref="chartB" class="chart"></div></article>
      </section>

      <section class="workspace">
        <form class="panel" @submit.prevent="submit">
          <h2>新增记录</h2>
          <div class="form-grid">
            <label v-for="field in fields" :key="field.key">
              {{ field.label }}
              <select v-if="field.type === 'select'" v-model="form[field.key]" required>
                <option value="">请选择</option>
                <option v-for="item in field.options" :key="item">{{ item }}</option>
              </select>
              <input v-else v-model="form[field.key]" :type="field.type || 'text'" required />
            </label>
            <label>备注<textarea v-model="note" /></label>
            <button type="submit">保存并刷新</button>
          </div>
        </form>
        <section class="table-panel">
          <h2>明细列表</h2>
          <table>
            <thead><tr><th v-for="field in fields" :key="field.key">{{ field.label }}</th><th>备注</th></tr></thead>
            <tbody><tr v-for="record in filtered" :key="record.id"><td v-for="field in fields" :key="field.key">{{ record[field.key] }}</td><td class="note">{{ record.note }}</td></tr></tbody>
          </table>
        </section>
      </section>
    </div>
  </main>
</template>
